ARG BASE_IMAGE=runpod/pytorch:2.1.0-py3.10-cuda11.8.0-devel-ubuntu22.04
FROM ${BASE_IMAGE}

WORKDIR /workspace
RUN apt-get update && apt-get install -y git awscli && rm -rf /var/lib/apt/lists/*

# Ostris AI Toolkit base
RUN rm -rf /workspace/ai-toolkit && \
    git clone https://github.com/ostris/ai-toolkit.git /workspace/ai-toolkit && \
    pip install --upgrade pip && \
    pip install -r /workspace/ai-toolkit/requirements.txt && \
    pip install -e /workspace/ai-toolkit

ENV AITOOLKIT_HOME=/workspace/ai-toolkit
